# collect_logs_minimal.yml
- name: View service logs (UI-only)
  hosts: "{{ target_hosts | default('all') }}"
  become: true
  gather_facts: false

  tasks:
    - name: Show brief systemd status (optional)
      ansible.builtin.command:
        argv: [systemctl, status, "--no-pager", "--lines=20", "{{ service_unit }}"]
      register: svc_status
      changed_when: false
      failed_when: false

    - name: Print service status
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ svc_status.stdout_lines }}"

    - name: Show journal logs (since OR last N)
      ansible.builtin.shell: |
        set -o pipefail
        journalctl -u {{ service_unit | quote }} \
        {% if (since | default('')) | length > 0 -%}
          --since {{ since | quote }}
        {%- else -%}
          -n {{ (tail_lines | default(300)) | int }}
        {%- endif %} \
        --no-pager --output=short-iso
      args:
        executable: /bin/bash
      register: jc
      changed_when: false
      failed_when: false

    - name: Print logs
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ jc.stdout_lines }}"
