---
- name: Prepare to build
  hosts: localhost
  tasks:
    - name: Install requirements
      ansible.builtin.apt:
        name:
          - build-essential
          - cmake
          - clang
          - openssl
          - libssl-dev
          - zlib1g-dev
          - gperf
          - wget
          - git
          - curl
          - liblz4-dev
          - pkg-config
          - libsecp256k1-dev
          - libsodium-dev
          - libhiredis-dev
          - python3-dev
          - libpq-dev
          - automake
          - libjemalloc-dev
          - lsb-release
          - software-properties-common
          - gnupg
          - autoconf
          - libtool
          - libmicrohttpd-dev
          - ccache
        state: present
      become: true

- name: Build binaries
  hosts: localhost
  tasks:
    - name: Remove CMakeCache.txt
      ansible.builtin.file:
        path: "{{ build_path }}/CMakeCache.txt"
        state: absent
    - name: Build ton-streaming-go
      ansible.builtin.shell: |
          mkdir -p {{ build_path }}
          cmake -DCMAKE_BUILD_TYPE=Release -S . -B {{ build_path }} > {{ build_path }}/prepare.log 2>&1
          cmake --build {{ build_path }} --parallel $(nproc) --target ton-streaming-go > {{ build_path }}/build.log 2>&1
      changed_when: true
      vars:
        service: "{{ services[item] }}"
      failed_when: build_result.rc != 0
      register: build_result

- name: Deploy services
  hosts: "{{ stack_name }}__streaming"
  become: true
  tasks:
    - name: Ensure binary directory
      ansible.builtin.file:
        path: "{{ deploy_path }}"
        recurse: true
        state: directory

    - name: Copy binaries
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0777"
        force: true
      with_items:
        - src: "{{ build_path }}/ton-streaming-go/ton-streaming-go"
          dest: "{{ deploy_path }}/{{ stack_name }}__streaming_api"
    
    - name: Update ldconfig
      ansible.builtin.shell: ldconfig

    - name: Setup ton-streaming-go service
      ansible.builtin.template:
        src: "ansible/systemd.service.j2"
        dest: "{{ systemd_service_path }}/{{ service_name }}.service"
        mode: "0644"
        force: true
      vars:
        service: "{{ services[item] }}"
        service_name: "{{ stack_name }}__{{ item }}"
        start_cmd: "{{ deploy_path }}/{{ service_name }} {{ service.additional_args }}"
      with_items:
        - streaming_api

    - name: Restart and enable streaming services
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: restarted
        enabled: true
        force: true
        daemon_reload: true
      vars:
        service_name: "{{ stack_name }}__{{ item }}"
      throttle: 1
      become: true
      with_items:
       - streaming_api
