- name: Prepare to build
  hosts: builder
  tasks:
    - name: Install requirements
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        name:
          - build-essential
          - cmake
          - clang
          - openssl
          - libssl-dev
          - zlib1g-dev
          - gperf
          - wget
          - git
          - curl
          - liblz4-dev
          - pkg-config
          - libsecp256k1-dev
          - libsodium-dev
          - libhiredis-dev
          - python3-dev
          - libpq-dev
          - automake
          - libjemalloc-dev
          - lsb-release
          - software-properties-common
          - gnupg
          - autoconf
          - libtool
          - libmicrohttpd-dev
          - ccache
          - rsync
        state: present

    - name: Ensure shared caches exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0775"
      loop:
        - "{{ ansible_env.HOME }}/.cache/ccache"
        - "{{ ansible_env.HOME }}/.cache/go-build"
        - "{{ ansible_env.HOME }}/.cache/gomod"

    - name: Ensure golang is installed
      ansible.builtin.include_role:
        name: geerlingguy.go
        apply:
          become: true
      vars:
        go_version: "1.24.7"
        go_checksum: "da18191ddb7db8a9339816f3e2b54bdded8047cdc2a5d67059478f8d1595c43f"

- name: Build ton-indexer binaries
  hosts: builder
  tasks:
    - name: Create temp workspace
      ansible.builtin.tempfile:
        state: directory
        suffix: ton-indexer
      register: builddir

    - block:
        - name: Copy project to builder from . to "{{ builddir.path }}" with rsync
          ansible.builtin.synchronize:
            src: "{{ hostvars['localhost'].repo_dir }}/"
            dest: "{{ builddir.path }}"
            rsync_opts:
              - "--exclude=.git"
              - "--exclude=artifacts"
            recursive: yes
            delete: no

        - name: Build ton-emulate-go and ton-trace-task-emulator
          ansible.builtin.shell: |
            set -e
            cmake -DCMAKE_BUILD_TYPE=Release \
                  -S . -B "{{ builddir.path }}/build" \
                  -G Ninja \
                  -DCMAKE_C_COMPILER_LAUNCHER=ccache \
                  -DCMAKE_CXX_COMPILER_LAUNCHER=ccache 
            cmake --build "{{ builddir.path }}/build" \
                  --parallel {{ ansible_facts.processor_vcpus | default(2) }} \
                  --target ton-emulate-go ton-trace-task-emulator
          args:
            chdir: "{{ builddir.path }}"
          environment:
            CCACHE_DIR: "{{ ansible_env.HOME }}/.cache/ccache"
            CCACHE_BASEDIR: "{{ builddir.path }}"
            CCACHE_SLOPPINESS: "file_macro"
            GOCACHE: "{{ ansible_env.HOME }}/.cache/go-build"
            GOMODCACHE: "{{ ansible_env.HOME }}/.cache/gomod"
            GOFLAGS: "-modcacherw"

        - name: Collect built binaries
          ansible.builtin.fetch:
            src: "{{ builddir.path }}/build/{{ item }}"
            dest: "artifacts/"
            flat: true
          loop:
            - "ton-emulate-go/ton-emulate-go"
            - "ton-index-worker/ton-marker/libton-marker.so"
            - "ton-index-worker/ton-trace-task-emulator/ton-trace-task-emulator"
      always:
        - name: Cleanup workspace
          ansible.builtin.file:
            path: "{{ builddir.path }}"
            state: absent

- name: Deploy services
  hosts: "{{ stack_name }}__emulation"
  become: true
  tags: [deploy]
  tasks:
    - name: Ensure binary directory
      ansible.builtin.file:
        path: "{{ deploy_path }}"
        recurse: true
        state: directory

    - name: Install requirements
      ansible.builtin.apt:
        name:
          - python3-pip
          - python3-venv
          - dnsutils
          - libpq-dev
          - libsecp256k1-dev
          - libsodium-dev
          - libhiredis-dev
          - redis
        state: present
      become: true

    - name: Copy binaries
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0777"
      with_items:
        - src: "artifacts/ton-emulate-go"
          dest: "{{ deploy_path }}/{{ stack_name }}__emulate_api"
        - src: "artifacts/ton-trace-task-emulator"
          dest: "{{ deploy_path }}/{{ stack_name }}__trace_task_emulator"

    - name: Install libton-marker.so
      ansible.builtin.copy:
        src: "artifacts/libton-marker.so"
        dest: "/usr/lib/libton-marker.so"
        mode: "0644"

    - name: Refresh linker cache
      ansible.builtin.command: ldconfig
      changed_when: false

    - name: Copy python module
      ansible.builtin.copy:
        src: indexer
        dest: "{{ deploy_path }}"

    - name: Setup venv
      ansible.builtin.pip:
        requirements: "{{ deploy_path }}/indexer/requirements.txt"
        virtualenv: "{{ deploy_path }}/venv"
        virtualenv_command: "python3 -m venv"
        extra_args: "--no-cache-dir"
    
    - name: Setup emulate_api and trace_task_emulator services 
      ansible.builtin.template:
        src: "ansible/systemd.service.j2"
        dest: "{{ systemd_service_path }}/{{ service_name }}.service"
        mode: "0644"
      vars:
        service: "{{ services[item] }}"
        service_name: "{{ stack_name }}__{{ item }}"
        start_cmd: "{{ deploy_path }}/{{ service_name }} {{ service.additional_args }}"
      with_items:
        - emulate_api
        - trace_task_emulator
    
    - name: Setup action classifier service
      ansible.builtin.template:
        src: "ansible/systemd.service.j2"
        dest: "{{ systemd_service_path }}/{{ service_name }}.service"
        mode: "0644"
      vars:
        service: "{{ services.action_classifier }}"
        service_name: "{{ stack_name }}__{{ service.service_name }}"
        start_cmd: "{{ deploy_path }}/venv/bin/python3 {{ deploy_path }}/indexer/event_classifier.py {{ service.additional_args }}"
      no_log: true
      notify: restart service
    
    - name: Start and enable service redis-server
      ansible.builtin.systemd:
        name: redis-server
        state: started
        enabled: true
        force: true
        daemon_reload: true
      throttle: 1

    - name: Restart and enable emulation services
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: restarted
        enabled: true
        force: true
        daemon_reload: true
      vars:
        service_name: "{{ stack_name }}__{{ item }}"
      throttle: 1
      with_items:
       - emulate_api
       - trace_task_emulator
       - action_classifier
