version: '3.9'

x-index-pg-access: &index-pg-access
  POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
  POSTGRES_PORT: ${POSTGRES_PORT:-5432}
  POSTGRES_USER: ${POSTGRES_USER:-postgres}
  POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
  POSTGRES_DB: ${POSTGRES_DB:-ton_index}

services:
  index-api-go:
    image: ${DOCKER_REGISTRY:-localhost:5000}/ton-index-go:${IMAGE_TAG:?}
    build:
      context: ton-index-go
      dockerfile: Dockerfile
    secrets:
      - postgres_password
    command: -prefork -threads ${TON_INDEXER_WORKERS:-1}
    init: true
    ports:
      - target: 8081
        published: ${TON_INDEXER_API_PORT:-8081}
        protocol: tcp
        mode: host
    environment: 
      <<: *index-pg-access
      TON_INDEXER_API_ROOT_PATH: ${TON_INDEXER_API_ROOT_PATH:-/}
      TON_INDEXER_API_PORT: ${TON_INDEXER_API_PORT:-8081}
      TON_INDEXER_TON_HTTP_API_ENDPOINT: ${TON_INDEXER_TON_HTTP_API_ENDPOINT:-}
      TON_INDEXER_IS_TESTNET: ${TON_INDEXER_IS_TESTNET:-0}
    deploy:
      mode: replicated
      replicas: ${SWARM_REPLICAS:-1}
      placement:
        constraints:
          - "node.labels.${TONCENTER_ENV:?}.indexer-cpp.api-go==true"
    networks:
      internal:
      toncenter-global:
        aliases:
          - ${TONCENTER_ENV:?}-indexer-cpp-api-go

networks:
  internal:
    attachable: true
    external: false
    driver_opts:
      com.docker.network.driver.mtu: 1350
  toncenter-global:
    external: true

secrets:
  postgres_password:
    file: ${POSTGRES_PASSWORD_FILE:-private/postgres_password}
