version: '3.9'


x-indexer-environment: &indexer-environment
  POSTGRES_DIALECT: ${POSTGRES_DIALECT:-postgresql+asyncpg}
  POSTGRES_HOST:
  POSTGRES_PORT:
  POSTGRES_USER:
  POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
  POSTGRES_DBNAME:
  TON_INDEXER_API_ROOT_PATH:

services:
  alembic:
    image: ${DOCKER_REGISTRY:-docker.io/toncenter}/ton-indexer-cpp:${IMAGE_TAG:-latest}
    build:
      context: indexer
      dockerfile: Dockerfile
    environment: *indexer-environment 
    secrets:
      - postgres_password
    command: alembic upgrade head-1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.${TONCENTER_ENV:-mainnet}.indexer-cpp.api==true"
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 60s
    networks:
      internal:

networks:
  internal:
    attachable: true
    external: false
    driver_opts:
      com.docker.network.driver.mtu: 1350

secrets:
  postgres_password:
    file: ${POSTGRES_PASSWORD_FILE:-private/postgres_password}
