---
- name: Restart Prometheus
  ansible.builtin.systemd_service:
    name: "{{ prometheus_service_name }}"
    state: restarted
  when: prometheus_restart_enabled | bool
  listen: restart prometheus
